language: node_js
node_js:
  - 14
  - 16
sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libprotobuf-dev
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - curl -LO https://github.com/riemann/riemann/releases/download/0.3.6/riemann_0.3.6_all.deb
  - sudo dpkg --install riemann_0.3.6_all.deb
  - sudo service riemann start
  - until sudo lsof -Pi :5555 -sTCP:LISTEN -t; do true; done > /dev/null
script:
  - npm run lint
  - npm test
